#!/bin/bash
#SBATCH --job-name=UpDownSelect
#SBATCH --time=5-00:00:00
#SBATCH --cpus-per-task=200
#SBATCH --mem-per-cpu=4G

INPUT_DIR=${1:-ncbi_dataset}
OUTPUT_DIR=${2:-data}
THREADS=${3:-12}
SAMPLE_SIZE=${4:-3}
TAXON=${5:-"staphylococcus aureus"}
PTHREADS=$((THREADS / 4))

build_directory_structure() {
    mkdir -p $OUTPUT_DIR/bakta2
    }

fetch_genome_data() {
    local INPUT_DIR=$1
    local TAXON=$2
    datasets download genome taxon "$TAXON" \
        --assembly-level complete \
        --exclude-atypical \
        --assembly-source 'RefSeq' \
        --dehydrated \
        --filename $INPUT_DIR.zip
    unzip -n $INPUT_DIR.zip
    rm $INPUT_DIR.zip
    datasets rehydrate --directory .
    }

download_bakta_db() {
    bakta_db download --output resources --type light
    }

annotate_genomes() {
    local INPUT_DIR=$1
    local OUTPUT_DIR=$2
    local SAMPLE_SIZE=$3
    find $INPUT_DIR -type f | shuf -n $SAMPLE_SIZE > parallel_input.tmp
    parallel -j $PTHREADS \
        "bakta \
            --db resources/db-light/ \
            --prefix {/.} \
            --threads 4 \
            --output $OUTPUT_DIR/{/.}" {} \
        :::: parallel_input.tmp
    rm parallel_input.tmp
    }

### FUNCTION CALLS ###

# build_directory_structure
# fetch_genome_data $INPUT_DIR "$TAXON"
# download_bakta_db
annotate_genomes $INPUT_DIR $OUTPUT_DIR/bakta2 $SAMPLE_SIZE